[versions]
gradle-starter = "0.92.0"
maven-junit = "6.0.2"
maven-assertj = "3.27.7"
google-androidx-core = "1.17.0"
google-androidx-annotation = "1.9.1"
google-appcompat = "1.7.1"
google-constraintLayout = "2.2.1"
google-material = "1.13.0"
google-lifecycle = "2.10.0"
google-activity = "1.12.2"
google-fragment = "1.8.9"
maven-leakcanary = "2.14"
gradle-doctor = "0.12.1"
maven-binarycompatiblity = "0.18.1"
maven-paparazzi = "2.0.0-alpha02"
maven-vanniktech-maven-publish = "0.36.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "maven-junit" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "maven-assertj" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "google-androidx-core" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "google-androidx-annotation" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "google-lifecycle" }
androidx-activity-core = { module = "androidx.activity:activity-ktx", version.ref = "google-activity" }
androidx-fragment-core = { module = "androidx.fragment:fragment-ktx", version.ref = "google-fragment" }
appcompat-core = { module = "androidx.appcompat:appcompat", version.ref = "google-appcompat" }
constraintlayout-core = { module = "androidx.constraintlayout:constraintlayout", version.ref = "google-constraintLayout" }
material-core = { module = "com.google.android.material:material", version.ref = "google-material" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "maven-leakcanary" }
vanniktech-maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "maven-vanniktech-maven-publish" }

[plugins]
starter-config = { id = "com.starter.config", version.ref = "gradle-starter" }
starter-versioning = { id = "com.starter.versioning", version.ref = "gradle-starter" }
starter-library-kotlin = { id = "com.starter.library.kotlin", version.ref = "gradle-starter" }
starter-library-android = { id = "com.starter.library.android", version.ref = "gradle-starter" }
starter-application-android = { id = "com.starter.application.android", version.ref = "gradle-starter" }
app-cash-paparazzi = { id = "app.cash.paparazzi", version.ref = "maven-paparazzi" }
osacky-doctor = { id = "com.osacky.doctor", version.ref = "gradle-doctor" }
kotlinx-binarycompatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "maven-binarycompatiblity" }
